blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'

urlpatterns = [
    url(r"^$", views.post_list, name="post_list"),
    url(r"^new/$", views.post_new, name="post_new"),
    url(r"^tag/(?P<tag_slug>[\w-]+)/$", views.post_list, name="post_list"),
    url(r"^post/(?P<pk>\d+)/$", views.post_detail_by_id, name="post_detail_by_id"),
    url(r"^post/(?P<slug>[\w-]+)/$", views.post_detail, name="post_detail"),
    url(r"^post/(?P<slug>[\w-]+)/edit/$", views.post_edit, name="post_edit"),
    url(r"^rss/$", views.RSSFeed(), name="rss"),
]

django_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView


urlpatterns = [
    url(r"^admin/", admin.site.urls),
    url(r"^", include("blog.urls", namespace="blog")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.db.models import Count, Max, Min
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager
from taggit.models import Tag
from tinymce.models import HTMLField

from .utils import unique_slug_generator


class Post(models.Model):
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(blank=True, unique=True)
    text = HTMLField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    tags = TaggableManager(blank=True)

    class Meta:
        ordering = ["-published_date"]

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"slug": self.slug})

    def save(self):
        if not self.slug:
            self.slug = unique_slug_generator(self)

        super().save()

    def publish(self, user):
        self.published_date = timezone.now()
        self.author = user
        self.save()
        return self

    def __str__(self):
        return self.title


def font_size(self, max_font=28, min_font=12):
    """ Calculate font size for tag based on it's occurrence
    """
    v = (
        Tag.objects.all()
        .annotate(c=Count("post"))
        .filter(c__gt=0)
        .aggregate(Min("c"), Max("c"))
    )
    max_tag, min_tag = v["c__max"], v["c__min"]
    try:
        step = (max_font - min_font) / float(max_tag - min_tag)
    except ZeroDivisionError:
        step = 1
    tag_count = Post.objects.filter(tags__name=self.name).count()
    size = int(min_font + (tag_count - min_tag) * step)

    return size


Tag.f = font_size

blog/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title", "text", "tags")

blog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.syndication.views import Feed
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse
from django.db.models import F, Q
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.utils.text import Truncator

from .forms import PostForm
from .models import Post


def post_list(request, tag_slug=None):
    if request.user.is_authenticated:
        list_ = Post.objects.order_by(F("published_date").desc(nulls_first=True))
    else:
        list_ = Post.objects.filter(published_date__lte=timezone.now())
    if tag_slug is not None:
        list_ = list_.filter(tags__slug=tag_slug)
    search_query = ""
    if request.GET.get("search"):
        search_query = request.GET.get("search")
        list_ = Post.objects.filter(
            Q(title__contains=search_query) | Q(text__contains=search_query)
        )
    paginator = Paginator(list_, 5)
    page = request.GET.get("page")
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:  # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:  # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)
    return render(
        None, "blog/post_list.html", {"posts": posts, "search_query": search_query}
    )


def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    tags = post.tags.names()
    if request.POST.get("action") == "delete":
        if request.user.is_authenticated:
            post.delete()
            return redirect("/")
        else:
            return redirect("/admin/login/?next=/post/" + slug)
    return render(request, "blog/post_detail.html", {"post": post, "tags": tags})


def post_detail_by_id(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return redirect("blog:post_detail", permanent=True, slug=post.slug)


@login_required(login_url="/admin/login/?next=/")
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.publish(request.user)
            form.save_m2m()
            return redirect("blog:post_detail", slug=post.slug)
    else:
        form = PostForm()
    return render(request, "blog/post_edit.html", {"form": form})


@login_required(login_url="/admin/login/?next=/")
def post_edit(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.publish(request.user)
            form.save_m2m()
            return redirect("blog:post_detail", slug=post.slug)
    else:
        form = PostForm(instance=post)
    return render(request, "blog/post_edit.html", {"form": form})


class RSSFeed(Feed):
    title = "django-blog"
    link = "/rss/"
    description = "Updates on sudnitsina.pythonanywhere.com."

    def items(self):
        return Post.objects.filter(published_date__lte=timezone.now())[:5]

    def item_description(self, item):
        return Truncator(item.text).words(20, html=True)

    def item_link(self, item):
        return reverse("blog:post_detail_by_id", kwargs={"pk": item.pk})

blog/templates/blog/base.html
{% load static %}
{% load pagination_filters %}
{% load side_panel %}
<html>
	<head>
		<title>BLOG</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="{% static 'css/new.css' %}">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css">
		<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
	</head>
	<body>
		<div id="header">
			<a id="logo" href="/">Django Blog</a>
			<div id="search">
				<form id="search-form">
					<input name="search" type="text">
					<input id="button-search" type="submit" value="">
				</form>
			</div>
			<a href="{% url 'blog:post_new' %}"><i id="plus" class="fa fa-plus-square"></i></a>
		</div>
		<div id="content">
		<div id="posts">
		{% block content %}
		{% endblock %}
		</div>
			<div class="sidemenu">
				<div class="block">
					<h2>Menu</h2>
					<ul>
						<li><li><a href="{% url 'blog:post_new' %}">new post</a></li>
						<li><a href="/">all notes</a></li>
						<a href="{% url 'blog:rss' %}" rel="alternate" type="application/rss+xml">RSS <i class="fa fa-rss"></i></a>
					</ul>
				</div>
				{% last_posts %}
			</div>
		</div>
		<div id="pagination">
		<p>
			{% if posts.has_previous %}
			←<a href="?page={{ posts.previous_page_number }}{% if search_query != '' %}&search={{ search_query }} {% endif %}">предыдущая</a>
			{% endif %}
			{% if posts.has_next %}
			<a href="?page={{ posts.next_page_number }}{% if search_query != '' %}&search={{ search_query }} {% endif %}">следующая</a>→
			{% endif %}
		</p>
		{% if posts.has_other_pages %}
		<a href="?page=1{% if search_query != '' %}&search={{ search_query }} {% endif %}">←</a>
		{% for page in posts.paginator.num_pages|truncate:posts.number %}
		{% if page == posts.number %} {{page}}
		{% else %} <a href="?page={{page}}{% if search_query != '' %}&search={{ search_query }} {% endif %}">{{page}}</a> {% endif %} {% endfor %}
		<a href="?page={{ posts.paginator.num_pages }}{% if search_query != '' %}&search={{ search_query }} {% endif %}"> → </a>
		{% endif %}
		{% comment  %}
		<ul class="menu_top paginator">
		{% if posts.has_previous %}
			<li> <a href="?page=1"><<</a> </li>
			<li>  <a href="?page={{ posts.previous_page_number }}">{{ posts.previous_page_number }}</a> </li>
			{% endif %}
			{% if posts.has_other_pages %}<li>   <a style="color: #000000"  href="">{{ posts.number }}</a></li> {% endif %}
			{% if posts.has_next %}
			<li> <a href="?page={{ posts.next_page_number }}">      {{ posts.next_page_number }}</a> </li>
			<!--li> <a href="?page={{ posts.next_page_number|add:1 }}">{{ posts.next_page_number|add:1 }}</a></li-->
			<li> <a href="?page={{ posts.paginator.num_pages }}">    >> </a></li>           {% endif %}
		{% endcomment %}
		</ul>
		</div>
	</body>

</html>

blog/templates/blog/last_posts.html
<div class="block">
<h2>Последние</h2>
<ul>
{% for i in post_list %}
  <li><a href="{{ i.get_absolute_url }}"> {{ i.title }} </a> <br>
  <div class="date"> {{ i.published_date }} </div>
{% empty %}
  <li>В блоге еще нет записей</li>
{% endfor %}
</ul>
</div>

<div class="block" style="text-align: center">
  <h2> Теги </h2>
  {% for tag in cloud %}
  <a href="{% url 'blog:post_list' tag_slug=tag.slug %}" style="font-size: {{tag.f}}px; margin: 2px ">{{ tag.name }}</a>
  {% endfor %}
</div>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="post">
	<span class="delete">
		<a href='#deletionDialog'><i class="fa fa-trash"></i></a>
	</span>
	<span class="edit">
		<a href="{% url 'blog:post_edit' slug=post.slug %}"><i class="fa fa-pencil"></i></a>
	</span>
	<h1>{{ post.title }}</h1>
	{% if post.published_date %}
	<div class="date">
		<i class="fa fa-calendar"></i> {{ post.published_date}}
	</div>
	{% endif %}
	{% if post.tags.names %}
	<div class="tag">
		<i class="fa fa-tags"></i>
		{% for tag in post.tags.all %}
		<a href="{% url 'blog:post_list' tag_slug=tag.slug %}">{{ tag.name }}</a>
		{% endfor %}
	</div>
	{% endif %}
	<p>{{ post.text|safe|linebreaksbr }}</p>
	<div id="deletionDialog" class="dialog">
		<div>
			<a class="close" href="">x</a>
			<span style="margin: auto">Удалить пост "{{ post.title }}"? </span>
			<form method="POST" >{% csrf_token %}
				<input type=hidden name="id" value="{{ post.pk }}">
				<input type="submit" name="action" value="delete" onclick="location.href = '#'">
				<input type="button" value="cancel" onclick="location.href='#'">
			</form>
		</div>
	</div>

	<div id="disqus_thread"></div>
	<script>
	var disqus_config = function () {
	//this.page.url = {{ request.get_host }}; // Replace PAGE_URL with your page's canonical URL variable
	this.page.identifier = "{{ post.pk }}"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
	};

	(function() { // DON'T EDIT BELOW THIS LINE
	var d = document, s = d.createElement('script');
	s.src = 'https://sudnitsina.disqus.com/embed.js';
	s.setAttribute('data-timestamp', +new Date());
	(d.head || d.body).appendChild(s);
	})();
	</script>
	<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

</div>

{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="block">
  <form method="POST" class="post-form">
    {% csrf_token %}
    <table id="postform">
      {{ form.as_table}}
      <tr>
        <td colspan=2 style='text-align: right;'>
          <button type="submit" class="save btn btn-default">Save</button>
        </td>
      </tr>
    </table>
  </form>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% comment %} {% load pagination_tags %} {% endcomment %}

{% block content %}
{% if posts %}
{% for post in posts %}
<div class="post">
	<div class="post-header">
		<h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
		<div class="date"><i class="fa fa-calendar"></i> {{ post.published_date}}</div>
		{% if post.tags.names %}
		<div class="tag">
			<i class="fa fa-tags"></i>
			{% for tag in post.tags.all %}
			<a href="{% url 'blog:post_list' tag_slug=tag.slug%}">{{ tag.name }}</a>
      {% endfor %}
		</div>
		{% endif %}
	</div>
	{{ post.text|safe|linebreaksbr|truncatewords_html:80 }}<br>
	<a href="{{ post.get_absolute_url }}">Читать далее</a>
</div>
{% endfor %}
{% else %}
<div class="post">
	<p>Ничего не найдено</p>
</div>
{% endif %}
{% endblock content %}